name: simple_auth
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-76.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  analyzer: ^4.6.0
  dio: ^4.0.4
  json_serializable: ^6.1.4
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.15
  device_info: ^2.0.3
  get_it: ^7.2.0
  equatable: ^2.0.3 
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/Roboto-Medium.ttf
           weight: 600
         - asset: assets/fonts/Roboto-Regular.ttf
           weight: 500
         - asset: assets/fonts/Roboto-Light.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Thin.ttf
           weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg